# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ashiq/minindn"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4192"
    vb.cpus = "4"
    vb.name = "mini-ndn_box"
  end
end